//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.prom.by.adapters;

import android.content.Context;

public final class ItemAdapter_
    extends ItemAdapter
{

    private Context context_;

    private ItemAdapter_(Context context) {
        super(context);
        context_ = context;
        init_();
    }

    public static ItemAdapter_ getInstance_(Context context) {
        return new ItemAdapter_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
