//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.prom.by;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemClickListener;
import android.widget.ListView;
import android.widget.ProgressBar;
import android.widget.TextView;
import com.prom.by.R.layout;
import com.prom.by.adapters.OrderAdapter_;
import com.prom.by.helpers.DataProvider_;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class OrderListActivity_
    extends OrderListActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_order_list);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        orderAdapter = OrderAdapter_.getInstance_(this);
        dataProvider = DataProvider_.getInstance_(this);
        getOrders();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static OrderListActivity_.IntentBuilder_ intent(Context context) {
        return new OrderListActivity_.IntentBuilder_(context);
    }

    public static OrderListActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new OrderListActivity_.IntentBuilder_(fragment);
    }

    public static OrderListActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new OrderListActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        ordersList = ((ListView) hasViews.findViewById(com.prom.by.R.id.orders));
        empty = ((TextView) hasViews.findViewById(android.R.id.empty));
        progressBar = ((ProgressBar) hasViews.findViewById(com.prom.by.R.id.progress));
        {
            AdapterView<?> view = ((AdapterView<?> ) hasViews.findViewById(com.prom.by.R.id.orders));
            if (view!= null) {
                view.setOnItemClickListener(new OnItemClickListener() {


                    @Override
                    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                        OrderListActivity_.this.ordersItemClicked(position);
                    }

                }
                );
            }
        }
        setAdapter();
    }

    @Override
    public void showOrders() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                OrderListActivity_.super.showOrders();
            }

        }
        );
    }

    @Override
    public void showError() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                OrderListActivity_.super.showError();
            }

        }
        );
    }

    @Override
    public void showProgress() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                OrderListActivity_.super.showProgress();
            }

        }
        );
    }

    @Override
    public void fetchFromServer() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    OrderListActivity_.super.fetchFromServer();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, OrderListActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            fragment_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, OrderListActivity_.class);
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, OrderListActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public OrderListActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent_, requestCode);
                } else {
                    if (context_ instanceof Activity) {
                        ((Activity) context_).startActivityForResult(intent_, requestCode);
                    } else {
                        context_.startActivity(intent_);
                    }
                }
            }
        }

    }

}
