//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.prom.by.views;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import com.prom.by.R.layout;
import com.prom.by.adapters.ItemAdapter_;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class SingleOrderFragment_
    extends SingleOrderFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_single_order, container, false);
        }
        return contentView_;
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        itemAdapter = ItemAdapter_.getInstance_(getActivity());
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static SingleOrderFragment_.FragmentBuilder_ builder() {
        return new SingleOrderFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        orderAddress = ((TextView) hasViews.findViewById(com.prom.by.R.id.order_address));
        orderEmail = ((TextView) hasViews.findViewById(com.prom.by.R.id.order_email));
        orderOrderer = ((TextView) hasViews.findViewById(com.prom.by.R.id.order_orderer));
        orderItems = ((LinearLayoutList) hasViews.findViewById(com.prom.by.R.id.order_items));
        orderCompany = ((TextView) hasViews.findViewById(com.prom.by.R.id.order_company));
        orderDate = ((TextView) hasViews.findViewById(com.prom.by.R.id.order_date));
        orderId = ((TextView) hasViews.findViewById(com.prom.by.R.id.order_id));
        orderPrice = ((TextView) hasViews.findViewById(com.prom.by.R.id.order_phone));
        populateFragment();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public SingleOrderFragment build() {
            SingleOrderFragment_ fragment_ = new SingleOrderFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
